name: 'Issue Manager'
description: ''
author: 'hawkeye116477'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    default: '${{ github.token }}'
  configuration-path:
    description: 'Path to the configuration file'
    default: '.github/issue-manager.yml'
runs:
  using: 'node16'
  main: 'dist/index.js'
