name: 'Issue Manager'
description: ''
author: 'hawkeye116477'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    default: '${{ github.token }}'
  configuration-path:
    description: 'Path to the configuration file'
    default: '.github/issue-manager.yml'
  completed-label:
    description: 'Label for completed issues'
  not-planned-label:
    description: 'Label for issues, which solving is not planned'
runs:
  using: 'node16'
  main: 'dist/index.js'
